swagger: "2.0"
info:
  title: 微服务
  version: ""
host: localhost:8000
basePath: /api
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /score:
    get:
      tags:
      - Score
      summary: 成绩列表
      description: 成绩列表
      operationId: Score#ScoreList
      parameters:
      - name: sortField
        in: query
        description: 排序字段 默认createdAt
        required: false
        type: string
        enum:
        - class
        - name
        - score
        - subject
        - createdAt
      - name: cursor
        in: query
        description: cursor of page
        required: true
        type: integer
      - name: limit
        in: query
        description: limit of items
        required: true
        type: integer
        maximum: 100
      - name: sortOrder
        in: query
        description: 排序方式 默认desc
        required: false
        type: string
        enum:
        - asc
        - desc
      - name: name
        in: query
        description: 姓名
        required: false
        type: string
      - name: class
        in: query
        description: 班级
        required: false
        type: string
      - name: scores
        in: query
        description: 分数
        required: false
        type: integer
      - name: subject
        in: query
        description: 科目
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ScoreScoreListResponseBody'
            required:
            - errcode
            - errmsg
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ScoreScoreListBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ScoreScoreListInternalServerErrorResponseBody'
      schemes:
      - http
  /score/{id}:
    get:
      tags:
      - Score
      summary: 成绩详情
      description: 成绩详情
      operationId: Score#ScoreDetail
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ScoreScoreDetailResponseBody'
            required:
            - errcode
            - errmsg
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ScoreScoreDetailBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ScoreScoreDetailInternalServerErrorResponseBody'
      schemes:
      - http
  /score/upload:
    post:
      tags:
      - Score
      summary: 上传学生成绩文件
      description: 上传学生成绩文件
      operationId: Score#Upload
      parameters:
      - name: Content-Type
        in: header
        description: Content-Type header, must define value for multipart boundary.
        required: false
        type: string
        default: multipart/form-data; boundary=goa
        pattern: multipart/[^;]+; boundary=.+
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ScoreUploadResponseBody'
            required:
            - errcode
            - errmsg
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ScoreUploadBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ScoreUploadInternalServerErrorResponseBody'
      schemes:
      - http
definitions:
  GradeResultResponseBody:
    title: 'Mediatype identifier: graderesult; view=default'
    type: object
    properties:
      class:
        type: string
        description: 班级
        example: Molestiae voluptatem ducimus.
      createdAt:
        type: string
        description: 创建时间
        example: Nisi maxime consectetur sapiente optio maiores atque.
      id:
        type: string
        description: ID
        example: Unde tempora aliquid rerum ut quasi illum.
      name:
        type: string
        description: 姓名
        example: Commodi ut ipsam fugiat aut.
      score:
        type: integer
        description: 得分
        example: 4339585000005291484
        format: int64
      subject:
        type: string
        description: 科目
        example: Aut molestiae dolores est impedit.
      updatedAt:
        type: string
        description: 更新时间
        example: Facere quia eligendi optio non sunt autem.
    description: 分数信息 (default view)
    example:
      class: Quia nemo ut voluptate quisquam quibusdam.
      createdAt: Qui magni sed.
      id: Aut qui dolor.
      name: Ut saepe eius iure ut blanditiis voluptatibus.
      score: 4175551651020622815
      subject: Voluptatem maiores.
      updatedAt: Corporis eaque asperiores quia.
    required:
    - id
    - class
    - name
    - score
    - subject
    - createdAt
    - updatedAt
  ScoreScoreDetailBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: ScoreDetail_bad_request_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreScoreDetailInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: ScoreDetail_internal_server_error_Response_Body result type (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreScoreDetailResponseBody:
    title: ScoreScoreDetailResponseBody
    type: object
    properties:
      data:
        $ref: '#/definitions/GradeResultResponseBody'
      errcode:
        type: integer
        description: 错误码
        example: 0
        minimum: 0
        maximum: 999999
      errmsg:
        type: string
        description: 错误消息
        example: ""
    example:
      data:
        class: Est quos tempore temporibus consequuntur aliquid quaerat.
        createdAt: Suscipit labore est laborum a.
        id: Magni eos repudiandae incidunt molestiae.
        name: Est sit amet architecto rerum.
        score: 3831988211228176154
        subject: Quis qui alias.
        updatedAt: Aliquid id itaque quo dolores sit.
      errcode: 0
      errmsg: ""
    required:
    - errcode
    - errmsg
  ScoreScoreListBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: ScoreList_bad_request_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreScoreListInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: ScoreList_internal_server_error_Response_Body result type (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreScoreListResponseBody:
    title: ScoreScoreListResponseBody
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/GradeResultResponseBody'
        description: 结果
        example:
        - class: Est quos tempore temporibus consequuntur aliquid quaerat.
          createdAt: Suscipit labore est laborum a.
          id: Magni eos repudiandae incidunt molestiae.
          name: Est sit amet architecto rerum.
          score: 3831988211228176154
          subject: Quis qui alias.
          updatedAt: Aliquid id itaque quo dolores sit.
        - class: Est quos tempore temporibus consequuntur aliquid quaerat.
          createdAt: Suscipit labore est laborum a.
          id: Magni eos repudiandae incidunt molestiae.
          name: Est sit amet architecto rerum.
          score: 3831988211228176154
          subject: Quis qui alias.
          updatedAt: Aliquid id itaque quo dolores sit.
        - class: Est quos tempore temporibus consequuntur aliquid quaerat.
          createdAt: Suscipit labore est laborum a.
          id: Magni eos repudiandae incidunt molestiae.
          name: Est sit amet architecto rerum.
          score: 3831988211228176154
          subject: Quis qui alias.
          updatedAt: Aliquid id itaque quo dolores sit.
        - class: Est quos tempore temporibus consequuntur aliquid quaerat.
          createdAt: Suscipit labore est laborum a.
          id: Magni eos repudiandae incidunt molestiae.
          name: Est sit amet architecto rerum.
          score: 3831988211228176154
          subject: Quis qui alias.
          updatedAt: Aliquid id itaque quo dolores sit.
      errcode:
        type: integer
        description: 错误码
        example: 0
        minimum: 0
        maximum: 999999
      errmsg:
        type: string
        description: 错误消息
        example: ""
      nextCursor:
        type: integer
        description: 下一页游标
        example: 4601501107571180770
        format: int64
      total:
        type: integer
        description: 总记录数
        example: 1311315517379826286
        format: int64
    example:
      data:
      - class: Est quos tempore temporibus consequuntur aliquid quaerat.
        createdAt: Suscipit labore est laborum a.
        id: Magni eos repudiandae incidunt molestiae.
        name: Est sit amet architecto rerum.
        score: 3831988211228176154
        subject: Quis qui alias.
        updatedAt: Aliquid id itaque quo dolores sit.
      - class: Est quos tempore temporibus consequuntur aliquid quaerat.
        createdAt: Suscipit labore est laborum a.
        id: Magni eos repudiandae incidunt molestiae.
        name: Est sit amet architecto rerum.
        score: 3831988211228176154
        subject: Quis qui alias.
        updatedAt: Aliquid id itaque quo dolores sit.
      errcode: 0
      errmsg: ""
      nextCursor: 2282735861372885604
      total: 6278135676317512283
    required:
    - errcode
    - errmsg
  ScoreUploadBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Upload_bad_request_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreUploadInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Upload_internal_server_error_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  ScoreUploadResponseBody:
    title: ScoreUploadResponseBody
    type: object
    properties:
      data:
        $ref: '#/definitions/SuccessResultResponseBody'
      errcode:
        type: integer
        description: 错误码
        example: 0
        minimum: 0
        maximum: 999999
      errmsg:
        type: string
        description: 错误消息
        example: ""
    example:
      data:
        ok: true
      errcode: 0
      errmsg: ""
    required:
    - errcode
    - errmsg
  SuccessResultResponseBody:
    title: 'Mediatype identifier: successresult; view=default'
    type: object
    properties:
      ok:
        type: boolean
        description: success
        example: true
    description: 成功信息 (default view)
    example:
      ok: true
    required:
    - ok
